import { Button } from '@mui/material'
import Head from 'next/head'
import React from 'react'
import styled from 'styled-components'

const StyleContainer = styled.div`
    height: 100vh;
    display: grid;
    place-items: center;
    background-color: #fff;
`
const StyleLoginContainer = styled.div`
    display: flex;
`


export default function Login() {
    return (
        <StyleContainer>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <StyleLoginContainer>
                <Button variant='outlined' onClick={() => { }}>
                    Login Google
                </Button>
            </StyleLoginContainer>
        </StyleContainer>
    )
}
